# Generated by Django 4.1.7 on 2023-02-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_phoneno_customuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='college',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
