# Generated by Django 4.1.7 on 2023-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0026_alter_jobs_embedded_location_url"),
        ("accounts", "0007_customuser_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="applied_jobs",
            field=models.ManyToManyField(error_messages="check3", to="Jobs.jobs"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, error_messages="check", max_length=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                default="", error_messages="check2", upload_to="accounts/profile"
            ),
        ),
    ]
