# Generated by Django 4.1.7 on 2023-03-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True, default="", upload_to="accounts/profile_photos"
            ),
        ),
    ]
