# Generated by Django 4.1.7 on 2023-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="Major_skill",
            field=models.CharField(
                default="",
                help_text="Eg: Frontend Dveloper and designer",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="about_me",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                default="", help_text="Hyderabad, India", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="interests",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="skills",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                upload_to="accounts/profile_photos",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="skills_tag",
            field=models.ManyToManyField(to="accounts.skills"),
        ),
    ]
