# Generated by Django 4.1.7 on 2023-03-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_skills_customuser_major_skill_customuser_about_me_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="facebook_link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="instagram_link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitter_link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="youtube_link",
            field=models.CharField(default="", max_length=255),
        ),
    ]
