# Generated by Django 4.1.7 on 2023-03-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0013_customuser_facebook_link_customuser_instagram_link_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.gender",
            ),
        ),
    ]
