# Generated by Django 4.1.7 on 2023-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_project_customuser_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="Major_skill",
            field=models.CharField(
                default="",
                help_text="Eg: Frontend Developer and designer",
                max_length=30,
            ),
        ),
    ]
