# Generated by Django 4.1.7 on 2023-03-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_customuser_major_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_images",
            field=models.ImageField(
                default="",
                upload_to="accounts/projects/<django.db.models.fields.CharField>/",
            ),
        ),
    ]
