# Generated by Django 4.1.7 on 2023-04-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_rename_gender_gender_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("feedback", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_recruiter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="source_link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="Major_skill",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Eg: Frontend Developer and designer",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="about_me",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hyderabad, India",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="facebook_link",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.gender_type",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="instagram_link",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interests",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="accounts/profile_photos",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="skills",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="twitter_link",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="youtube_link",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
