# Generated by Django 4.1.7 on 2023-04-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_feedback_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
    ]
