# Generated by Django 4.1.7 on 2023-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_alter_customuser_applied_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="projects",
            field=models.ManyToManyField(
                blank=True, default=None, to="accounts.project"
            ),
        ),
    ]
