# Generated by Django 4.1.7 on 2023-04-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_award_customuser_awards"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="salary",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
