# Generated by Django 4.1.7 on 2023-04-02 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_customuser_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dob",
            field=models.DateField(default=datetime.date(1980, 12, 31)),
        ),
    ]
