# Generated by Django 4.1.7 on 2023-04-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_customuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="qualification",
            field=models.CharField(
                default="",
                help_text="enter highest degree or currently persuing degree",
                max_length=100,
            ),
        ),
    ]
