# Generated by Django 4.1.7 on 2023-04-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_alter_customuser_cv_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="resume",
            field=models.FileField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                upload_to="accounts/resume",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cv",
            field=models.FileField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                upload_to="accounts/cv",
            ),
        ),
    ]
