# Generated by Django 4.1.7 on 2023-04-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_qualification_customuser_qualifications"),
    ]

    operations = [
        migrations.RemoveField(model_name="qualification", name="location",),
        migrations.RemoveField(model_name="qualification", name="score",),
    ]
