# Generated by Django 4.1.7 on 2023-04-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_workandexperience_customuser_work_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="qualifications",
            field=models.ManyToManyField(blank=True, to="accounts.qualification"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="work_experience",
            field=models.ManyToManyField(blank=True, to="accounts.workandexperience"),
        ),
    ]
