# Generated by Django 4.1.7 on 2023-04-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_alter_customuser_qualifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="experience",),
        migrations.RemoveField(model_name="customuser", name="qualification",),
        migrations.RemoveField(model_name="customuser", name="awards",),
        migrations.AddField(
            model_name="customuser",
            name="awards",
            field=models.ManyToManyField(blank=True, to="accounts.award"),
        ),
    ]
