# Generated by Django 4.1.7 on 2023-04-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0053_remove_customuser_about_me_remove_customuser_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="personal_information",),
        migrations.AddField(
            model_name="customuser",
            name="about_me",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hyderabad, India",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="facebook_link",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.gender_type",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="instagram_link",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="interests",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="languages",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="accounts/profile_photos",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="salary",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitter_link",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="youtube_link",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.DeleteModel(name="UserPersonalInformation",),
    ]
