# Generated by Django 4.1.7 on 2023-04-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="qualification",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hyderabad, India",
                max_length=255,
                null=True,
            ),
        ),
    ]
