# Generated by Django 4.1.7 on 2023-04-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0059_alter_customuser_cv_alter_customuser_profile_photo_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(name="skills", options={"ordering": ["name"]},),
        migrations.AlterField(
            model_name="qualification",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="workandexperience",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
