# Generated by Django 4.1.7 on 2023-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="src",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
