# Generated by Django 4.1.7 on 2023-04-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_alter_customuser_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser", old_name="youtube_link", new_name="linkedin_link",
        ),
    ]
