# Generated by Django 4.1.5 on 2023-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0002_remove_jobs_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
