# Generated by Django 4.1.7 on 2023-03-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0012_applicationform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="location",
            field=models.CharField(
                help_text="Enter company's embedded location from Google maps",
                max_length=255,
            ),
        ),
    ]
