# Generated by Django 4.1.7 on 2023-03-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0020_alter_jobs_embedded_location_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobs", name="tag",),
        migrations.AddField(
            model_name="jobs",
            name="Category",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="Jobs.tag"
            ),
        ),
    ]
