# Generated by Django 4.1.7 on 2023-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0021_remove_jobs_tag_jobs_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobs", name="Category",),
        migrations.AddField(
            model_name="jobs",
            name="tag",
            field=models.ManyToManyField(blank=True, to="Jobs.tag"),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="embedded_location_url",
            field=models.TextField(
                blank=True, help_text="Embeded url from maps of company"
            ),
        ),
    ]
