# Generated by Django 4.1.7 on 2023-03-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0029_jobs_no_of_openings"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicationform", name="job",),
    ]
