# Generated by Django 4.1.7 on 2023-03-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0030_remove_applicationform_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
