# Generated by Django 4.1.7 on 2023-03-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0031_alter_tag_name"),
    ]

    operations = [
        migrations.RenameModel(old_name="Job_Duration_type", new_name="Job_Duration",),
    ]
