# Generated by Django 4.1.7 on 2023-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0036_applicationform_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs_type", name="name", field=models.CharField(max_length=16),
        ),
    ]
