# Generated by Django 4.1.7 on 2023-04-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_award_customuser_awards"),
        ("Jobs", "0037_alter_jobs_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="skills_required",
            field=models.ManyToManyField(blank=True, default="", to="accounts.skills"),
        ),
    ]
