# Generated by Django 4.1.7 on 2023-04-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0039_alter_job_duration_options_alter_jobs_type_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="designation",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="jobs", name="salary", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="jobs", name="title", field=models.CharField(max_length=250),
        ),
    ]
