# Generated by Django 4.1.7 on 2023-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0041_alter_jobs_about_company_alter_jobs_about_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="default_job.png",
                null=True,
                upload_to="Jobs/job_logo",
            ),
        ),
    ]
