# Generated by Django 4.1.7 on 2023-04-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0042_alter_jobs_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs", name="title", field=models.CharField(max_length=250),
        ),
    ]
