# Generated by Django 4.1.7 on 2023-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0047_alter_jobs_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
