# Generated by Django 4.1.7 on 2023-04-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0051_alter_jobs_title"),
    ]

    operations = [
        migrations.AlterModelOptions(name="jobs", options={"ordering": ["title"]},),
        migrations.AlterField(
            model_name="jobs",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
