# Generated by Django 4.1.5 on 2023-02-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobs", name="slug",),
    ]
