# Generated by Django 4.1.7 on 2023-03-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0005_jobs_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="type",
            field=models.CharField(
                choices=[("Online", "Work-From-Home"), ("Offline", "From Office")],
                max_length=20,
            ),
        ),
    ]
