# Generated by Django 4.1.7 on 2023-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0006_alter_jobs_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs", name="date", field=models.DateField(auto_now_add=True),
        ),
    ]
