# Generated by Django 4.1.7 on 2023-03-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0010_jobs_logo"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobs", name="logo",),
    ]
