# Generated by Django 4.1.7 on 2023-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0013_alter_jobs_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="embedded_location_url",
            field=models.CharField(
                blank=True,
                help_text="Enter company's embedded location from Google maps exclude '<iframe>'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="location",
            field=models.CharField(
                help_text="Enter company's locaion main city name", max_length=255
            ),
        ),
    ]
