# Generated by Django 4.1.7 on 2023-03-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0016_jobs_embedded_location_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="embedded_location_url",
            field=models.TextField(
                blank=True,
                help_text="paste the embeded url from google maps of your company exclude <iframe>",
            ),
        ),
    ]
