# Generated by Django 4.1.7 on 2023-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0017_alter_jobs_embedded_location_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="location",
            field=models.CharField(
                help_text="Enter company's location (city name)", max_length=255
            ),
        ),
    ]
