# Generated by Django 4.1.7 on 2023-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0018_alter_jobs_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="embedded_location_url",
            field=models.TextField(
                blank=True, help_text="Embeded url from maps of company"
            ),
        ),
    ]
