# Generated by Django 4.1.7 on 2023-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0023_remove_jobs_tag_jobs_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="job_duration_type",
            field=models.CharField(
                choices=[("Temporary", "Part Time"), ("Permanent", "Full Time")],
                default="Full Time",
                max_length=20,
            ),
        ),
    ]
