# Generated by Django 4.1.7 on 2023-03-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0026_alter_jobs_embedded_location_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="logo",
            field=models.ImageField(default="", upload_to="Jobs/job_logo"),
        ),
    ]
