# Generated by Django 4.1.7 on 2023-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0028_applicationform_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="no_of_openings",
            field=models.IntegerField(default=10),
        ),
    ]
