# Generated by Django 4.1.7 on 2023-03-31 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0035_jobs_job_applied_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationform",
            name="job",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Jobs.jobs",
            ),
        ),
    ]
