# Generated by Django 4.1.7 on 2023-04-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0038_jobs_skills_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job_duration", options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(name="jobs_type", options={"ordering": ["name"]},),
        migrations.AlterModelOptions(name="tag", options={"ordering": ["name"]},),
    ]
