# Generated by Django 4.1.7 on 2023-04-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0044_alter_jobs_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
