# Generated by Django 4.1.7 on 2023-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0048_alter_jobs_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs", name="date", field=models.DateField(auto_now_add=True),
        ),
    ]
