# Generated by Django 4.1.7 on 2023-04-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0050_alter_jobs_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="title",
            field=models.CharField(default="", max_length=250),
        ),
    ]
