# Generated by Django 4.1.7 on 2023-04-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0052_alter_jobs_options_alter_jobs_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(name="jobs", options={"ordering": ["date"]},),
    ]
