# Generated by Django 4.1.7 on 2023-04-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0054_alter_jobs_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationform",
            name="resume",
            field=models.FileField(
                default="", max_length=255, upload_to="accounts/resume/"
            ),
        ),
    ]
