# Generated by Django 4.1.7 on 2023-02-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_age_remove_customuser_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='customuser',
            name='identifier',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
