# Generated by Django 4.1.5 on 2023-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_phoneno_customuser_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="identifier",),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
