# Generated by Django 4.1.7 on 2023-03-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_applied_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(default="", upload_to="accounts/profile"),
        ),
    ]
