# Generated by Django 4.1.7 on 2023-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_customuser_profile_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(default="", upload_to="accounts/profile_photos"),
        ),
    ]
