# Generated by Django 4.1.7 on 2023-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_gender_customuser_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("project_description", models.TextField(default="")),
                (
                    "project_images",
                    models.ImageField(
                        upload_to="accounts/projects/<django.db.models.fields.CharField>/"
                    ),
                ),
                ("skills_used", models.ManyToManyField(to="accounts.skills")),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="projects",
            field=models.ManyToManyField(default=None, to="accounts.project"),
        ),
    ]
