# Generated by Django 4.1.7 on 2023-03-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_subsribeemails"),
    ]

    operations = [
        migrations.RenameModel(old_name="SubsribeEmails", new_name="SubscribeEmails",),
    ]
