# Generated by Django 4.1.7 on 2023-03-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_rename_subsribeemails_subscribeemails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribeemails",
            name="email",
            field=models.CharField(max_length=254),
        ),
    ]
