# Generated by Django 4.1.7 on 2023-03-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_subscribeemails_email"),
    ]

    operations = [
        migrations.DeleteModel(name="SubscribeEmails",),
    ]
