# Generated by Django 4.1.7 on 2023-04-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0024_feedback_customuser_is_recruiter_project_source_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
