# Generated by Django 4.1.7 on 2023-04-01 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_customuser_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date created"
            ),
        ),
    ]
