# Generated by Django 4.1.7 on 2023-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0036_applicationform_job"),
        ("accounts", "0027_alter_customuser_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="applied_jobs",
            field=models.ManyToManyField(blank=True, to="Jobs.jobs"),
        ),
    ]
