# Generated by Django 4.1.7 on 2023-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_customuser_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="languages",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
