# Generated by Django 4.1.7 on 2023-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_customuser_cv_alter_customuser_profile_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cv",
            field=models.FileField(
                blank=True, default="", null=True, upload_to="accounts/cv"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="accounts/profile_photos",
            ),
        ),
    ]
