# Generated by Django 4.1.7 on 2023-04-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_rename_feild_of_study_qualification_field_of_study"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkandExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("joining_date", models.DateField()),
                ("leaving_date", models.DateField(blank=True, null=True)),
                ("experience_description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="work_experience",
            field=models.ManyToManyField(
                blank=True, null=True, to="accounts.workandexperience"
            ),
        ),
    ]
