# Generated by Django 4.1.7 on 2023-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_rename_major_skill_customuser_major_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser", name="dob", field=models.DateField(),
        ),
    ]
