# Generated by Django 4.1.7 on 2023-04-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_alter_customuser_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
