# Generated by Django 4.1.7 on 2023-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
