# Generated by Django 4.1.7 on 2023-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_customuser_qualification_alter_customuser_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cv",
            field=models.FileField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                upload_to="accounts/cv/",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="accounts/profile_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="resume",
            field=models.FileField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                upload_to="accounts/resume/",
            ),
        ),
    ]
