# Generated by Django 4.1.7 on 2023-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0061_alter_gender_type_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("content_html", models.TextField(editable=False)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
