# Generated by Django 4.1.7 on 2023-04-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_blog_src_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser", options={"ordering": ["-is_recruiter", "username"]},
        ),
    ]
